# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightfit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=4)),
                ('test_score', models.IntegerField()),
                ('activities', models.CharField(max_length=254)),
                ('education_interest', models.CharField(max_length=254)),
                ('school_int', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education_interest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_int',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test_score',
        ),
    ]
