# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-07 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightfit_app', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='school',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
