# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-13 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightfit_app', '0005_auto_20190809_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='majors',
        ),
        migrations.AddField(
            model_name='school',
            name='majors',
            field=models.ManyToManyField(related_name='schools', to='rightfit_app.Major'),
        ),
    ]
